### ISSUE TITLE
no discovery working.

### ISSUE THREAD

**Issue by bennydente** [rimram31/dz_smarthome#1]
I'm trying the discovery but I received  these error.
can you help?

'directive': KeyError
Traceback (most recent call last):
  File "/var/task/lambda.py", line 49, in event_handler
    response =  AlexaSmartHome.handle_message(dzRemote, request)
  File "/var/task/AlexaSmartHome.py", line 318, in handle_message
    message = message[API_DIRECTIVE]
KeyError: 'directive'

**Comment by rimram31** [comment]
This skill is to be used closely with Alexa, the code expect a complete Alexa payload. Or perhaps you make some misconfiguration, please read and follow carefully the documentation provided.

I will not be able to provide specific support here, please join domoticz forum and dedicated post ([https://www.domoticz.com/forum/viewtopic.php?f=69&t=25946#p199376](url)) where users have installed successfully this skill.
