### ISSUE TITLE
Private VPN

### ISSUE THREAD

**Issue by grasuoare** [rimram31/dz_smarthome#4]
Hi!

Plugin works well on my raspberry pi with domoticz.

Could you please share about how to use it with a private VPN server used on the raspberry pi? In my case i use pivpn and i really don't want to get unsecured with the web port opened.

Thank you!

**Comment by rimram31** [comment]
Hi,

Unfortunately there is no way to build an Alexa skill without a public available endpoint. This is not related to alexicz but required by design by Amazon => https://developer.amazon.com/fr/docs/smarthome/understand-the-smart-home-skill-api.html
