### ISSUE TITLE
Discovery works in test, but not from Alexa App or website

### ISSUE THREAD

**Issue by FearNaBoinne** [rimram31/dz_smarthome#8]
I followed the HOWTO as much as possible (the UI has changed significantly) and when I run manual tests as shown in the HOWTO, I see it connect and successfully retrieve the devices. I can also switch a light that way.

However when I scan for new devices in the Alexa App, I do NOT see anything happening... Neither in the Lambda log groups, nor on my Domoticz host...

I have no clue where to start troubleshooting!

**Comment by rimram31** [comment]
Sorry I'm no more working on this repo
