### ISSUE TITLE
Revised pdf with more up-to-date screenshots and a few very minor changes

### ISSUE THREAD

**Issue by sd5445fr** [rimram31/dz_smarthome#9]
Hi. First of all, I'd like to thank you for all the time you put into the Alexicz project. I've just installed it, but found the the screenshots were fairly outdated. I've revised your .pdf and brought it back up to date. Since I didn't have the original document you used to export it to pdf, I used LibreOffice Draw. 

I'm including both the updated pdf file and the LibreOffice Draw file I used in case you'd like to make changes. I've never done anything like this before, so don't really know how to contact you.

I'm sure future Alexicz users will appreciate it. 
[HOWTO-CreateAlexiczskill-R3.odg](https://github.com/rimram31/dz_smarthome/files/9883290/HOWTO-CreateAlexiczskill-R3.odg)
[HOWTO-CreateAlexiczskill-R3.pdf](https://github.com/rimram31/dz_smarthome/files/9883293/HOWTO-CreateAlexiczskill-R3.pdf)

Mille mercis !

~sd5445

**Comment by rimram31** [comment]
Thanks for your contribution for the community. I've add your files to the root dir.

It seems you're french ... so merci beaucoup !
